services:
    nginx:
        container_name: laravel_nginx
        image: "nginx:latest"
        ports:
            - "${APP_PORT:-8080}:80"
            - "${APP_SSL_PORT:-443}:443"
        volumes:
            - "./:/var/www/html"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        networks:
            - laravel_app
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        depends_on:
            - mysql
            - redis
        links:
            - "php-fpm"

    php-fpm:
        container_name: laravel_php
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                - "UID=${UID:-1000}"
                - "GID=${GID:-1000}"
        volumes:
            - "./:/var/www/html"
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        networks:
            - laravel_app
        links:
            - mysql
            - redis
        depends_on:
            - mysql
            - redis

    mysql:
        container_name: laravel_mysql
        image: "mysql/mysql-server:8.0"
        restart: unless-stopped
        tty: true
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - "laravel-mysql:/var/lib/mysql"
        networks:
            - laravel_app
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-p${DB_PASSWORD}"
            retries: 3
            timeout: 5s

    phpmyadmin:
        container_name: laravel_phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: "${DB_PORT:-3306}"
        ports:
            - "${PHPMYADMIN_PORT:-8081}:80"
        networks:
            - laravel_app
        links:
            - mysql
        depends_on:
            - mysql

    redis:
        container_name: laravel_redis
        image: "redis:alpine"
        ports:
            - "${REDIS_PORT:-6379}:6379"
        volumes:
            - "sail-redis:/data"
        networks:
            - laravel_app
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    redisinsight:
        container_name: laravel_redisinsight
        image: redislabs/redisinsight:latest
        restart: always
        ports:
            - "${REDISINSIGHT_PORT:-5540}:5540"
        networks:
            - laravel_app
        depends_on:
            - redis

    mailhog:
        container_name: laravel_mailhog
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "${MAILHOG_PORT:-8025}:8025"
        networks:
            - laravel_app

networks:
    laravel_app:
        driver: bridge

volumes:
    laravel-mysql:
        driver: local
    sail-redis:
        driver: local
